const mongoose = require('mongoose');

const tourSchema = new mongoose.Schema({
  title: { type: String, required: true, trim: true },
  slug: { type: String, trim: true },
  category: { type: String, trim: true },
  destination: { type: String, trim: true },
  country: { type: String, trim: true, default: 'Nepal' },
  province: { type: String, trim: true },
  city: { type: String, trim: true },
  coverImage: { type: String, trim: true },
  galleryImages: [{ type: String, trim: true }],
  videos: [{ type: String, trim: true }],
  shortDescription: { type: String, trim: true },
  fullDescription: { type: String, trim: true },
  durationDays: { type: Number, default: 0 },
  durationNights: { type: Number, default: 0 },
  difficulty: { type: String, trim: true },
  maxTravelers: { type: Number, default: 0 },
  languages: [{ type: String, trim: true }],
  pickupLocation: { type: String, trim: true },
  googleMapsEmbedUrl: { type: String, trim: true },
  mapRouteDetails: { type: Object, default: {} },
  price: { type: Number, default: 0 },
  discount: { type: Number, default: 0 },
  featuredBadge: { type: Boolean, default: false },
  bestSellerBadge: { type: Boolean, default: false },
  recommendedBadge: { type: Boolean, default: false },
  remainingSeats: { type: Number, default: 0 },
  bookingStatus: { type: String, trim: true, default: 'Available' },
  tourGuideAssignment: { type: String, trim: true },
  vehicleAssignment: { type: String, trim: true },
  hotelAssignment: { type: String, trim: true },
  homepageVisibility: { type: Boolean, default: true },
  publishStatus: { type: String, trim: true, default: 'Published' },
  seoTitle: { type: String, trim: true },
  seoMetaDescription: { type: String, trim: true },
  urlSlug: { type: String, trim: true },
  availableDates: [{ type: String, trim: true }],
  highlights: [{ type: Object, default: {} }],
  itinerary: [{ type: Object, default: {} }],
  included: [{ type: Object, default: {} }],
  excluded: [{ type: Object, default: {} }],
  travelAdvice: [{ type: Object, default: {} }],
  faqs: [{ type: Object, default: {} }],
  reviews: { type: Object, default: { averageRating: 0, totalReviews: 0, ratingBreakdown: {}, customerPhotos: [], list: [] } },
  infoCards: { type: Object, default: {} }
}, { timestamps: true });

module.exports = mongoose.model('Tour', tourSchema);
